### ISSUE TITLE
customizable onscreen text 

### ISSUE THREAD

**Issue by svenzimmermann** [NU-ITS/mdm-image-viewer#1]
Thank you first for this excellent app. It works perfect. It also allows us to disable the Auto Sleep feature, which has always been causing problems for our students and teachers.

Feature Request:
For use on our school campus in germany the text in the AirPlay box is not optimal.
A very useful new feature would be an onscreen text customizable via app configuration profile or csv.

It would be great if you could integrate this feature in the next version.

Best regards
Sven Zimmermann

**Comment by qharouff** [comment]
edu.nebraska.ImageViewer.airplaySubtitle and edu.nebraska.ImageViewer.airplayDescription options for managed app config have been added in version 1.0.4 that allow for this customization. Check out the README page fore more details. Update availability still pending App Store review.
